parameters:  
  "service-dir":
    default: "sdk/communicationchatconfig"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    ## emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":    
    package-dir: "azure-communication-chat-config"
    package-name: "{package-dir}"  
    package-mode: dataplane
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.Communication.Chat.Config"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
  "@azure-tools/typespec-ts":
    package-dir: "azure-communication-chat-config-rest"
    generateMetadata: true
    generateTest: true
    packageDetails:
      name: "@azure-rest/azure-communication-chat-config-rest"
      description: "Azure.Communication.Chat.Config Service"
  "@azure-tools/typespec-java":
    package-dir: "azure-communication-chat-config"
    namespace: com.azure.communication.chat.config
